/**
 * AI Automation Locator & Script Builder - Content Script
 * Injected into the target page. Manages element highlighting, selection,
 * badge rendering, and DOM analysis.
 */

(function () {
  // Prevent duplicate injection
  if (window.hasAILocatorScriptInjected) return;
  window.hasAILocatorScriptInjected = true;

  let isInspecting = false;
  let isRecording = false;
  let hoveredElement = null;
  let selectedElements = []; // List of selected DOM elements
  let badgeElements = [];    // List of badge DOM elements drawn on page

  // Create UI overlay elements
  let hoverBox = null;
  let tooltip = null;

  function initUI() {
    if (!hoverBox) {
      hoverBox = document.createElement("div");
      hoverBox.className = "ai-inspector-hover-box";
      hoverBox.style.display = "none";
      document.body.appendChild(hoverBox);
    }

    if (!tooltip) {
      tooltip = document.createElement("div");
      tooltip.className = "ai-inspector-tooltip";
      tooltip.style.display = "none";
      document.body.appendChild(tooltip);
    }
  }

  function isDynamicId(id) {
    if (!id) return false;
    const dynamicPatterns = [
      /ember\d+/i,
      /react-\w+/i,
      /vue-\w+/i,
      /^[0-9_-]+$/,
      /\d{4,}/,                   // 4 or more consecutive digits
      /[a-f0-9]{8}-[a-f0-9]{4}/i, // UUID fragment
      /:r[0-9a-z]+:/i,            // React 18 useId format like :r0:
    ];
    return dynamicPatterns.some(pattern => pattern.test(id));
  }

  function isDynamicClass(cls) {
    if (!cls) return false;
    // Autogenerated CSS modules, Tailwind dynamic classes, or random hashes (like css-1abcde)
    const dynamicPatterns = [
      /^css-\w+/i,
      /Styled\w+/i,
      /^[a-z0-9]{8,12}$/i, // Random looking hash classes
      /\d{4,}/,
      /^Mui\w+/i, // Material UI generic classes
    ];
    return dynamicPatterns.some(pattern => pattern.test(cls));
  }

  function getRelativeXPath(ancestor, element) {
    if (ancestor === element) return "";
    const paths = [];
    for (let curr = element; curr && curr !== ancestor; curr = curr.parentNode) {
      let index = 0;
      let hasSiblings = false;
      for (let sibling = curr.previousSibling; sibling; sibling = sibling.previousSibling) {
        if (sibling.nodeName === curr.nodeName) {
          index++;
          hasSiblings = true;
        }
      }
      for (let sibling = curr.nextSibling; sibling; sibling = sibling.nextSibling) {
        if (sibling.nodeName === curr.nodeName) {
          hasSiblings = true;
          break;
        }
      }
      const tag = curr.nodeName.toLowerCase();
      const idxStr = (hasSiblings || index > 0) ? `[${index + 1}]` : "";
      paths.unshift(`${tag}${idxStr}`);
    }
    return paths.length ? "//" + paths.join("/") : "";
  }

  function getRelativeCSSSelector(ancestor, element) {
    if (ancestor === element) return "";
    const paths = [];
    for (let curr = element; curr && curr !== ancestor; curr = curr.parentNode) {
      const tag = curr.nodeName.toLowerCase();
      paths.unshift(tag);
    }
    return paths.join(" > ");
  }

  // Generate robust XPath
  function generateXPath(element) {
    if (!element) return "";
    
    // 1. If it has a stable ID, use it
    if (element.id && !isDynamicId(element.id)) {
      return `//*[@id="${element.id}"]`;
    }
    
    // 2. Check for stable data attributes
    const testAttributes = ["data-testid", "data-qa", "data-cy", "data-test", "testid"];
    for (const attr of testAttributes) {
      if (element.hasAttribute(attr)) {
        return `//*[@${attr}="${element.getAttribute(attr)}"]`;
      }
    }

    // 3. Dynamic Web Tables anchoring
    const cell = element.closest("td, th");
    const table = element.closest("table");
    if (cell && table) {
      const row = cell.closest("tr");
      if (row) {
        const siblings = Array.from(row.querySelectorAll("td, th"));
        let anchorCell = null;
        let anchorText = "";
        
        for (const sib of siblings) {
          const text = (sib.innerText || "").trim();
          if (text.length > 1 && text.length < 30 && !sib.querySelector("button, input, select, a")) {
            const matchRows = Array.from(table.querySelectorAll("tr")).filter(r => (r.innerText || "").includes(text));
            if (matchRows.length === 1) {
              anchorCell = sib;
              anchorText = text;
              break;
            }
          }
        }
        
        if (anchorCell && anchorText) {
          const anchorTextEscaped = anchorText.replace(/'/g, "\\'");
          const colIndex = siblings.indexOf(cell) + 1;
          
          if (element === cell) {
            return `//table//tr[td[contains(., '${anchorTextEscaped}')]]/td[${colIndex}]`;
          }
          
          const relativePath = getRelativeXPath(cell, element);
          return `//table//tr[td[contains(., '${anchorTextEscaped}')]]/td[${colIndex}]${relativePath}`;
        }
      }
    }

    // 4. If it's a button, link, or label with text, generate text-based XPath
    const tag = element.tagName.toLowerCase();
    if ((tag === "button" || tag === "a" || tag === "label" || (tag === "input" && (element.type === "button" || element.type === "submit"))) && element.innerText && element.innerText.trim().length > 0) {
      const text = element.innerText.trim();
      if (text.length > 0 && text.length < 50) {
        const textEscaped = text.replace(/'/g, "\\'");
        if (!text.includes('"') && !text.includes("'")) {
          return `//${tag === "input" ? "input" : tag}[text()='${textEscaped}']`;
        }
        return `//${tag === "input" ? "input" : tag}[contains(text(), '${textEscaped}')]`;
      }
    }

    // 5. Fallback: Walk up DOM
    const paths = [];
    let current = element;
    for (; current && current.nodeType === Node.ELEMENT_NODE; current = current.parentNode) {
      if (current.id && !isDynamicId(current.id)) {
        paths.unshift(`//*[@id="${current.id}"]`);
        break;
      }

      let foundDataAttr = false;
      for (const attr of testAttributes) {
        if (current.hasAttribute(attr)) {
          paths.unshift(`//*[@${attr}="${current.getAttribute(attr)}"]`);
          foundDataAttr = true;
          break;
        }
      }
      if (foundDataAttr) break;

      let index = 0;
      let hasSiblingsWithSameTag = false;
      
      for (let sibling = current.previousSibling; sibling; sibling = sibling.previousSibling) {
        if (sibling.nodeType === Node.DOCUMENT_TYPE_NODE) continue;
        if (sibling.nodeName === current.nodeName) {
          index++;
          hasSiblingsWithSameTag = true;
        }
      }
      
      for (let sibling = current.nextSibling; sibling; sibling = sibling.nextSibling) {
        if (sibling.nodeName === current.nodeName) {
          hasSiblingsWithSameTag = true;
          break;
        }
      }
      
      const tagName = current.nodeName.toLowerCase();
      const pathIndex = (hasSiblingsWithSameTag || index > 0) ? `[${index + 1}]` : "";
      paths.unshift(tagName + pathIndex);
    }
    
    return paths.length ? (paths[0].startsWith("//") ? paths.join("/") : "/" + paths.join("/")) : null;
  }

  // Generate CSS Selector
  function generateCSSSelector(element) {
    if (!element) return "";
    
    const testAttributes = ["data-testid", "data-qa", "data-cy", "data-test", "testid"];
    for (const attr of testAttributes) {
      if (element.hasAttribute(attr)) {
        return `[${attr}="${element.getAttribute(attr)}"]`;
      }
    }

    // Table cell relative positioning
    const cell = element.closest("td, th");
    const table = element.closest("table");
    if (cell && table) {
      const row = cell.closest("tr");
      if (row) {
        const siblings = Array.from(row.querySelectorAll("td, th"));
        let anchorCell = null;
        let anchorText = "";
        for (const sib of siblings) {
          const text = (sib.innerText || "").trim();
          if (text.length > 1 && text.length < 30 && !sib.querySelector("button, input, select, a")) {
            const matchRows = Array.from(table.querySelectorAll("tr")).filter(r => (r.innerText || "").includes(text));
            if (matchRows.length === 1) {
              anchorCell = sib;
              anchorText = text;
              break;
            }
          }
        }
        if (anchorCell && anchorText) {
          const colIndex = siblings.indexOf(cell) + 1;
          const cleanAnchorText = anchorText.replace(/"/g, '\\"');
          if (element === cell) {
            return `tr:has(td:has-text("${cleanAnchorText}")) > td:nth-child(${colIndex})`;
          }
          const relCSS = getRelativeCSSSelector(cell, element);
          return `tr:has(td:has-text("${cleanAnchorText}")) > td:nth-child(${colIndex}) ${relCSS}`.trim();
        }
      }
    }

    if (element.id && !isDynamicId(element.id)) {
      if (/^[0-9]/.test(element.id) || /[:.]/.test(element.id)) {
        return `[id="${element.id}"]`;
      }
      return `#${element.id}`;
    }
    
    const tag = element.tagName.toLowerCase();
    if (tag === "input") {
      if (element.getAttribute("name")) {
        return `input[name="${element.getAttribute("name")}"]`;
      }
      if (element.getAttribute("placeholder")) {
        const placeholderEscaped = element.getAttribute("placeholder").replace(/"/g, '\\"');
        return `input[placeholder="${placeholderEscaped}"]`;
      }
      if (element.getAttribute("type")) {
        return `input[type="${element.getAttribute("type")}"]`;
      }
    }

    if (element.getAttribute("aria-label")) {
      const ariaLabelEscaped = element.getAttribute("aria-label").replace(/"/g, '\\"');
      return `[aria-label="${ariaLabelEscaped}"]`;
    }
    if (element.getAttribute("title")) {
      const titleEscaped = element.getAttribute("title").replace(/"/g, '\\"');
      return `${tag}[title="${titleEscaped}"]`;
    }
    
    let selector = tag;
    if (element.className && typeof element.className === "string") {
      const classes = element.className
        .trim()
        .split(/\s+/)
        .filter(c => c && !c.startsWith("ai-") && !c.includes(":") && !isDynamicClass(c));
      if (classes.length > 0) {
        selector += "." + classes.slice(0, 3).join(".");
      }
    }
    
    if (["div", "span", "p"].includes(selector) && element.parentElement) {
      const parentSelector = generateCSSSelector(element.parentElement);
      if (parentSelector) {
        selector = `${parentSelector} > ${selector}`;
      }
    }
    
    return selector;
  }

  // Query elements using CSS selector or XPath
  function querySelectorAll(selector) {
    if (!selector) return [];
    
    // Check if it is an XPath
    if (selector.startsWith("//") || selector.startsWith("(/")) {
      const results = [];
      try {
        const query = document.evaluate(selector, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
        for (let i = 0; i < query.snapshotLength; i++) {
          results.push(query.snapshotItem(i));
        }
      } catch (e) {
        console.error("XPath evaluation failed:", e);
      }
      return results;
    }
    
    // Custom CSS selector parsing to support Playwright's :has-text() in standard browser queries
    if (selector.includes(":has-text(")) {
      try {
        // 1. Table row anchor format: tr:has(td:has-text("John Doe")) > td:nth-child(2) ...
        const tableCSSMatch = selector.match(/^tr:has\(td:has-text\("((?:[^"\\]|\\.)*)"\)\)(.*)$/);
        if (tableCSSMatch) {
          const anchorText = tableCSSMatch[1].replace(/\\"/g, '"');
          const remainder = tableCSSMatch[2].trim();
          
          const rows = Array.from(document.querySelectorAll("table tr"));
          const matchedRows = rows.filter(row => {
            const cells = Array.from(row.querySelectorAll("td, th"));
            return cells.some(cell => (cell.textContent || cell.innerText || "").trim().includes(anchorText));
          });
          
          const results = [];
          matchedRows.forEach(row => {
            if (!remainder) {
              results.push(row);
            } else {
              const querySel = remainder.startsWith(">") ? `:scope ${remainder}` : remainder;
              const found = Array.from(row.querySelectorAll(querySel));
              results.push(...found);
            }
          });
          return results;
        }

        // 2. Simple element:has-text("text") format
        const simpleHasTextMatch = selector.match(/^([a-zA-Z0-9#._-]+):has-text\("([^"]+)"\)(.*)$/);
        if (simpleHasTextMatch) {
          const baseTag = simpleHasTextMatch[1];
          const targetText = simpleHasTextMatch[2];
          const remainder = simpleHasTextMatch[3].trim();
          const candidates = Array.from(document.querySelectorAll(baseTag));
          const matched = candidates.filter(el => (el.textContent || el.innerText || "").includes(targetText));
          
          if (!remainder) return matched;
          
          const results = [];
          matched.forEach(parent => {
            const querySel = remainder.startsWith(">") ? `:scope ${remainder}` : remainder;
            const found = Array.from(parent.querySelectorAll(querySel));
            results.push(...found);
          });
          return results;
        }
      } catch (err) {
        console.error("Custom selector :has-text parsing failed:", err);
      }
    }
    
    // Default to CSS query selector
    return Array.from(document.querySelectorAll(selector));
  }


  // Highlight an element on hover
  function highlightElement(el) {
    if (!el || el === hoverBox || el === tooltip || el.classList.contains("ai-selection-badge")) {
      hideHighlight();
      return;
    }
    
    hoveredElement = el;
    initUI();

    const rect = el.getBoundingClientRect();
    const scrollX = window.scrollX;
    const scrollY = window.scrollY;

    // Position hover outline box
    hoverBox.style.width = `${rect.width}px`;
    hoverBox.style.height = `${rect.height}px`;
    hoverBox.style.left = `${rect.left + scrollX}px`;
    hoverBox.style.top = `${rect.top + scrollY}px`;
    hoverBox.style.display = "block";

    // Setup tooltip content
    let classStr = "";
    if (el.className && typeof el.className === "string") {
      classStr = el.className.split(/\s+/).filter(c => !c.startsWith("ai-")).map(c => `.${c}`).join("").substring(0, 40);
    }
    const idStr = el.id ? `#${el.id}` : "";
    const tagName = el.tagName.toLowerCase();

    tooltip.innerHTML = `<span class="tag-name">${tagName}</span><span class="id-name">${idStr}</span><span class="class-name">${classStr}</span>`;
    tooltip.style.display = "block";

    // Position tooltip above element, or below if not enough room
    const tooltipRect = tooltip.getBoundingClientRect();
    let tooltipTop = rect.top + scrollY - tooltipRect.height - 8;
    if (tooltipTop < scrollY + 5) {
      tooltipTop = rect.bottom + scrollY + 8;
    }
    let tooltipLeft = rect.left + scrollX + (rect.width / 2) - (tooltipRect.width / 2);
    if (tooltipLeft < scrollX + 5) tooltipLeft = scrollX + 5;

    tooltip.style.top = `${tooltipTop}px`;
    tooltip.style.left = `${tooltipLeft}px`;
  }

  function hideHighlight() {
    if (hoverBox) hoverBox.style.display = "none";
    if (tooltip) tooltip.style.display = "none";
    hoveredElement = null;
  }

  // Intercept click events on webpage
  function handlePageClick(e) {
    if (!isInspecting) return;
    
    // Ignore clicks on our own inspector overlays and badges
    if (e.target === hoverBox || e.target === tooltip || e.target.classList.contains("ai-selection-badge")) {
      return;
    }

    e.preventDefault();
    e.stopPropagation();

    const targetEl = e.target;
    selectElement(targetEl);
    
    // Auto-disable inspector after single selection (optional, but standard for extensions)
    // We can choose to keep it active for multiple clicks, let's keep it active so users can select multiple
    // but give them an easy toggle. To notify the side panel, we send a message.
  }

  // Extract metadata and select the element
  function selectElement(el) {
    if (selectedElements.includes(el)) {
      // If already selected, do nothing or remove it
      return;
    }

    selectedElements.push(el);
    el.classList.add("ai-inspected-element-selected");

    const elementIndex = selectedElements.length;
    
    // Extract element data
    const elementData = {
      index: elementIndex,
      tagName: el.tagName.toLowerCase(),
      id: el.id || "",
      name: el.getAttribute("name") || "",
      placeholder: el.getAttribute("placeholder") || "",
      type: el.getAttribute("type") || "",
      role: el.getAttribute("role") || "",
      innerText: el.innerText ? el.innerText.trim().substring(0, 80) : "",
      value: el.value || "",
      outerHTML: el.outerHTML.substring(0, 1000), // Snippet for AI analysis
      cssSelector: generateCSSSelector(el),
      xpath: generateXPath(el),
    };

    // Draw sequence badge on top of element
    drawBadge(el, elementIndex);

    // Send selection back to Side Panel
    chrome.runtime.sendMessage({
      action: "ELEMENT_SELECTED",
      element: elementData
    });
    
    hideHighlight();
  }

  // Draw sequence badge on webpage
  function drawBadge(el, index) {
    const rect = el.getBoundingClientRect();
    const badge = document.createElement("div");
    badge.className = "ai-selection-badge";
    badge.innerText = index;
    
    // Position badge at top-left of the target element
    const scrollX = window.scrollX;
    const scrollY = window.scrollY;
    badge.style.left = `${rect.left + scrollX - 10}px`;
    badge.style.top = `${rect.top + scrollY - 10}px`;
    
    // Remove selection when clicking badge
    badge.addEventListener("click", (e) => {
      e.stopPropagation();
      removeElementAt(index - 1);
    });

    document.body.appendChild(badge);
    badgeElements.push({ element: el, badgeEl: badge });
  }

  // Remove element at index
  function removeElementAt(idx) {
    if (idx < 0 || idx >= selectedElements.length) return;
    
    const el = selectedElements[idx];
    if (el) {
      el.classList.remove("ai-inspected-element-selected");
    }

    // Remove badge DOM element
    const match = badgeElements.find(b => b.element === el);
    if (match && match.badgeEl) {
      match.badgeEl.remove();
    }
    badgeElements = badgeElements.filter(b => b.element !== el);

    // Remove from array
    selectedElements.splice(idx, 1);

    // Shift indexes of subsequent badges
    rebuildBadges();

    // Notify sidepanel
    chrome.runtime.sendMessage({
      action: "ELEMENT_REMOVED",
      index: idx
    });
  }

  function rebuildBadges() {
    // Remove all old badges
    badgeElements.forEach(b => b.badgeEl.remove());
    badgeElements = [];

    // Re-draw all badges with new indices
    selectedElements.forEach((el, index) => {
      drawBadge(el, index + 1);
    });
  }

  // Clear all selections
  function clearSelections() {
    selectedElements.forEach(el => {
      if (el) el.classList.remove("ai-inspected-element-selected");
    });
    selectedElements = [];

    badgeElements.forEach(b => b.badgeEl.remove());
    badgeElements = [];

    hideHighlight();
  }

  // Scan and index interactive page elements for AI select query
  function indexPageElements() {
    // Select all potentially interactive elements
    const query = "button, input, a, textarea, select, [role='button'], [role='link'], [onclick]";
    const rawElements = Array.from(document.querySelectorAll(query));
    
    // Filter visible elements with valid interactive attributes or content
    const indexed = [];
    rawElements.forEach((el) => {
      // Simple visibility check
      const rect = el.getBoundingClientRect();
      if (rect.width === 0 || rect.height === 0 || window.getComputedStyle(el).display === "none" || window.getComputedStyle(el).visibility === "hidden") {
        return;
      }
      
      const text = el.innerText ? el.innerText.trim().substring(0, 50) : "";
      const id = el.id || "";
      const className = typeof el.className === "string" ? el.className.split(/\s+/).filter(c => !c.startsWith("ai-")).join(" ") : "";
      
      indexed.push({
        tag: el.tagName.toLowerCase(),
        id: id,
        name: el.getAttribute("name") || "",
        text: text,
        type: el.getAttribute("type") || "",
        placeholder: el.getAttribute("placeholder") || "",
        role: el.getAttribute("role") || "",
        class: className,
        // We temporarily store element reference, we will retrieve by index
        ref: el
      });
    });

    // Save references globally so we can highlight them later when AI specifies which ones to select
    window.indexedElementsReferences = indexed.map(item => item.ref);

    // Return serializable structure
    return indexed.map((item, index) => ({
      index: index,
      tag: item.tag,
      id: item.id,
      name: item.name,
      text: item.text,
      type: item.type,
      placeholder: item.placeholder,
      role: item.role,
      class: item.class
    }));
  }

  // Handle events
  document.addEventListener("mouseover", (e) => {
    if (!isInspecting) return;
    highlightElement(e.target);
  });

  document.addEventListener("click", handlePageClick, true);

  // Message receiver
  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    console.log("[content] received message:", message);
    if (message.action === "SET_INSPECTING") {
      isInspecting = message.enabled;
      if (!isInspecting) {
        hideHighlight();
      } else {
        initUI();
      }
      sendResponse({ status: "OK", inspecting: isInspecting });
    } 
    
    else if (message.action === "CLEAR_SELECTIONS") {
      clearSelections();
      sendResponse({ status: "OK" });
    } 
    
    else if (message.action === "REMOVE_SELECTION") {
      removeElementAt(message.index);
      sendResponse({ status: "OK" });
    } 
    
    else if (message.action === "GET_PAGE_ELEMENTS") {
      const elementsList = indexPageElements();
      sendResponse({ elements: elementsList });
    } 
    
    else if (message.action === "HIGHLIGHT_ELEMENT_INDEX") {
      const idx = message.index;
      if (window.indexedElementsReferences && window.indexedElementsReferences[idx]) {
        const el = window.indexedElementsReferences[idx];
        selectElement(el);
        // Scroll element into view
        el.scrollIntoView({ behavior: "smooth", block: "center" });
        sendResponse({ status: "OK", tag: el.tagName.toLowerCase() });
      } else {
        sendResponse({ status: "ERROR", message: "Element index not found" });
      }
    }
    
    else if (message.action === "SET_RECORDING") {
      isRecording = message.enabled;
      sendResponse({ status: "OK", recording: isRecording });
    }
    
    else if (message.action === "VERIFY_SELECTOR") {
      const selector = message.selector;
      try {
        const matches = querySelectorAll(selector);
        matches.forEach(el => {
          el.classList.remove("ai-flash-highlight");
          void el.offsetWidth; // Trigger reflow to restart animation if needed
          el.classList.add("ai-flash-highlight");
          setTimeout(() => el.classList.remove("ai-flash-highlight"), 1200);
        });
        sendResponse({ status: "OK", count: matches.length });
      } catch (err) {
        sendResponse({ status: "ERROR", message: err.message });
      }
    }
    
    return true; // Keep message channel open for async response
  });

  // -------------------------------------------------------------
  // SESSION RECORDER INTERCEPTORS
  // -------------------------------------------------------------
  function recordStep(el, action, value) {
    // Prevent duplicate logs in a short duration
    const now = Date.now();
    if (el.lastRecordedTime && (now - el.lastRecordedTime < 300)) {
      return;
    }
    el.lastRecordedTime = now;
    
    const elementData = {
      tagName: el.tagName.toLowerCase(),
      id: el.id || "",
      name: el.getAttribute("name") || "",
      placeholder: el.getAttribute("placeholder") || "",
      type: el.getAttribute("type") || "",
      role: el.getAttribute("role") || "",
      innerText: el.innerText ? el.innerText.trim().substring(0, 80) : "",
      outerHTML: el.outerHTML.substring(0, 1000),
      cssSelector: generateCSSSelector(el),
      xpath: generateXPath(el),
      action: action,
      value: value,
      label: el.id ? `#${el.id}` : `${el.tagName.toLowerCase()}${el.innerText ? ` "${el.innerText.trim().substring(0, 15)}"` : ""}`
    };
    
    chrome.runtime.sendMessage({
      action: "ELEMENT_RECORDED",
      element: elementData
    });
  }

  // Intercept user clicks during recording
  document.addEventListener("click", (e) => {
    if (!isRecording) return;
    
    // Ignore clicks on overlays, badges, and tooltips
    if (e.target === hoverBox || e.target === tooltip || e.target.classList.contains("ai-selection-badge")) {
      return;
    }
    
    const el = e.target;
    
    // Filter to interactive elements
    const isInteractive = el.tagName === "BUTTON" || 
                          el.tagName === "A" || 
                          (el.tagName === "INPUT" && !["text", "email", "password", "number", "tel", "url"].includes(el.type)) ||
                          el.hasAttribute("onclick") || 
                          el.getAttribute("role") === "button";
                          
    if (isInteractive) {
      recordStep(el, "click", "");
    }
  }, true); // Capture phase

  // Capture input changes when user finishes editing (blur)
  document.addEventListener("blur", (e) => {
    if (!isRecording) return;
    
    const el = e.target;
    const isTextInput = el.tagName === "INPUT" && ["text", "email", "password", "number", "tel", "url"].includes(el.type || "text");
    const isTextArea = el.tagName === "TEXTAREA";
    const isSelect = el.tagName === "SELECT";
    
    if (isTextInput || isTextArea || isSelect) {
      const val = el.value || "";
      recordStep(el, isSelect ? "click" : "type", val);
    }
  }, true); // Capture phase (blur does not bubble)

})();
